/** Strings for the design-reference pass on Move stock, Ask, State, All India and Settings. Same keys in both languages. */
const en = {
  // Move stock
  mvEyebrow: "District logistics", mvEyebrowSub: "Moving stock between facilities",
  mvSub: "Suggested by the optimiser: stock from facilities with extra to facilities running short, matched by distance and days of stock",
  segProposed: "Proposed", segTransit: "In transit", segDelivered: "Delivered", segNeeds: "Needs",
  search: "Search medicine or facility", noMatch: "Nothing matches that search.",
  deliveredEmpty: "Delivered transfers appear here once a facility confirms arrival.",
  proposedEmpty: "No transfer to suggest right now: nothing is running short, or no nearby facility has more than 21 days of stock to spare.",
  needsTitle: "Needs", needsSub: "Facilities under their resupply threshold",
  mapTitle: "Route", mapSub: "Pick a transfer to see its route; red dots are facilities under a week of stock",
  donor: "From, has extra", recipient: "To, running short", donorAfter: "Giver after", recipientAfter: "Receiver after",
  crossDistrict: "cross-district", markDelivered: "Mark delivered",
  // Ask
  askEyebrow: "District analytics", askEyebrowSub: "Questions in plain words",
  askTitle: "Ask the district", askSub: "Answers come from the district's ledgers through checked, read-only queries",
  answerTitle: "Answer", inspectSql: "Inspect SQL", hideSql: "Hide SQL", verifiedQuery: "Verified read-only query", copy: "Copy", copied: "Copied",
  recordsTitle: (n: number) => `Records (${n})`, noRecords: "This answer has no rows to show.", chartTitle: "Comparison",
  historyTitle: "Earlier questions", historySub: (n: number) => `${n} asked in this session. Open one to see its answer again.`, historyOpen: "Show answer", historyClear: "Clear history", rowsShort: (n: number) => `${n} rows`,
  // State
  stEyebrow: "State overview", stSub: (n: number) => `${n} districts · district scores, cross-district approvals and escalations`,
  viewLeague: "View district league",
  tileAlert: "Districts under alert", tileAlertSub: (n: number) => `Score under 60 (watch or at risk), of ${n}`,
  tileStock: "Median stock", tileStockSub: "Months of stock, median across districts",
  tileBeds: "State bed occupancy", tileBedsSub: (o: number, b: number) => `${o.toLocaleString("en-IN")} occupied of ${b.toLocaleString("en-IN")} beds`,
  tilePending: "Cross-district transfers", tilePendingSub: "Waiting for state approval",
  months: "months", mapTitle2: "District resilience map", lowest: "Lowest",
  approvalsTitle: "Cross-district approvals", approvalsSub: "Stock moving from one district to another needs state approval",
  reasonLbl: "Reason", rejectLbl: "Decline", rejected: "Declined", approvedLbl: "Approved",
  approvalsLoading: "Running the optimiser across the worst districts",
  approvalsEmpty: "No cross-district transfer is needed in the worst districts right now.",
  escEmpty: "None yet. District Magistrates escalate from their weekly brief.",
  allDistricts: "All districts",
  // League
  lgEyebrow: "State league", lgSub: "Every district ranked by resilience score; select a district to open its Today screen",
  filterName: "Filter districts", tierAll: "All", tierRes: "Resilient", tierWatch: "Watch", tierRisk: "At risk", noneAtRisk: "No district is at risk: every score is 45 or higher. The lowest are listed under Watch.", noneWatch: "No district is on watch.",
  inspect: "Open", colFacilities: "Facilities", noDistricts: "No district matches.",
  // India
  inEyebrow: "All India", inSub: "State and district stock from the HMIS district ledgers; PHC-level detail for the demo states",
  tileStates: "States reporting", tileStatesSub: (m: string) => m,
  tileNatStock: "Median months of stock", tileNatStockSub: "Median across reporting states",
  tileUnder: "Districts under a month", tileUnderSub: "Share of districts with under one month of stock",
  // Settings
  seEyebrow: "System", seTitle: "Settings and data provenance", seSub: "Who you are, which data you see, what-if tests, and where every number comes from",
  reset: "Reset to defaults", resetHint: "Default role and district, real data, no scenario",
  secRole: "Role", secBasis: "Data basis", secWhatIf: "What-if scenario", secFed: "Federated learning", secHealth: "Data health", secProv: "Where each number comes from",
  basisRealTitle: "Real HMIS ledgers", basisRealDesc: "District stock as the Ministry published it, latest complete month March 2020 (FY 2020-21 provisional for 16 states).",
  basisSimTitle: "Simulated to March 2026", basisSimDesc: "Each district's real series continued with its own seasonality and delivery pattern. Used on the India view and the store stock book only.",
  basisNote: "Facility-level stock on every other screen is simulated and seeded from the real district ledgers.",
  scenarioNone: "No scenario", scenarioNoneDesc: "Current figures, no stress applied.",
  scenarioOnly: (u: string) => `Applies to ${u}`, allUnits: "all states",
  intensity: "Intensity", active: "Active",
  // Federated
  fedRows: "Rows that left a node", fedRowsSub: "Measured at the aggregators",
  fedNodes: "Nodes in this tier", fedNodesSub: (r: number) => `${r} rounds of averaging`,
  fedAuc: "Federated AUC", fedAucSub: (l: string) => `vs ${l} trained alone`,
  runLiveRound: "Run a live round", running: "Running", replayLbl: "Replay", nodesTitle: "Nodes",
};
const hi: typeof en = {
  mvEyebrow: "ज़िला लॉजिस्टिक्स", mvEyebrowSub: "सुविधाओं के बीच स्टॉक भेजना",
  mvSub: "ऑप्टिमाइज़र के सुझाव: ज़्यादा स्टॉक वाली सुविधाओं से कमी वाली सुविधाओं तक, दूरी और स्टॉक के दिनों के आधार पर",
  segProposed: "प्रस्तावित", segTransit: "रास्ते में", segDelivered: "पहुँचे", segNeeds: "ज़रूरतें",
  search: "दवा या सुविधा खोजें", noMatch: "इस खोज से कुछ नहीं मिला।",
  deliveredEmpty: "सुविधा के पहुँचने की पुष्टि करने पर पहुँचे स्थानांतरण यहाँ दिखेंगे।",
  proposedEmpty: "अभी सुझाने को कोई स्थानांतरण नहीं: या तो किसी चीज़ की कमी नहीं है, या पास की किसी सुविधा के पास 21 दिन से ज़्यादा का स्टॉक नहीं है।",
  needsTitle: "ज़रूरतें", needsSub: "आपूर्ति सीमा से नीचे की सुविधाएँ",
  mapTitle: "रास्ता", mapSub: "रास्ता देखने के लिए कोई स्थानांतरण चुनें; लाल बिंदु एक हफ़्ते से कम स्टॉक वाली सुविधाएँ हैं",
  donor: "से, ज़्यादा स्टॉक", recipient: "को, कमी", donorAfter: "देने वाले के बाद", recipientAfter: "पाने वाले के बाद",
  crossDistrict: "अंतर-ज़िला", markDelivered: "पहुँचा चिह्नित करें",
  askEyebrow: "ज़िला विश्लेषण", askEyebrowSub: "सरल शब्दों में प्रश्न",
  askTitle: "ज़िले से पूछें", askSub: "उत्तर ज़िले के लेजर से जाँची हुई, केवल-पढ़ने वाली क्वेरी द्वारा आते हैं",
  answerTitle: "उत्तर", inspectSql: "SQL देखें", hideSql: "SQL छिपाएँ", verifiedQuery: "जाँची हुई केवल-पढ़ने वाली क्वेरी", copy: "कॉपी करें", copied: "कॉपी हुआ",
  recordsTitle: (n: number) => `रिकॉर्ड (${n})`, noRecords: "इस उत्तर में दिखाने के लिए पंक्तियाँ नहीं हैं।", chartTitle: "तुलना",
  historyTitle: "पहले पूछे गए प्रश्न", historySub: (n: number) => `इस सत्र में ${n} प्रश्न। उत्तर दोबारा देखने के लिए कोई प्रश्न खोलें।`, historyOpen: "उत्तर देखें", historyClear: "इतिहास साफ़ करें", rowsShort: (n: number) => `${n} पंक्तियाँ`,
  stEyebrow: "राज्य का सार", stSub: (n: number) => `${n} ज़िले · ज़िला स्कोर, अंतर-ज़िला स्वीकृतियाँ और एस्केलेशन`,
  viewLeague: "ज़िला तालिका देखें",
  tileAlert: "अलर्ट वाले ज़िले", tileAlertSub: (n: number) => `${n} में से, स्कोर 60 से कम (निगरानी या जोखिम)`,
  tileStock: "मध्य स्टॉक", tileStockSub: "स्टॉक के महीने, ज़िलों का मध्य",
  tileBeds: "राज्य बिस्तर भराव", tileBedsSub: (o: number, b: number) => `${b.toLocaleString("en-IN")} में से ${o.toLocaleString("en-IN")} भरे`,
  tilePending: "अंतर-ज़िला स्थानांतरण", tilePendingSub: "राज्य स्वीकृति की प्रतीक्षा",
  months: "महीने", mapTitle2: "ज़िला सुदृढ़ता नक्शा", lowest: "सबसे कम",
  approvalsTitle: "अंतर-ज़िला स्वीकृतियाँ", approvalsSub: "एक ज़िले से दूसरे ज़िले में जाने वाले स्टॉक के लिए राज्य की स्वीकृति चाहिए",
  reasonLbl: "कारण", rejectLbl: "अस्वीकार", rejected: "अस्वीकृत", approvedLbl: "स्वीकृत",
  approvalsLoading: "सबसे कमज़ोर ज़िलों में ऑप्टिमाइज़र चल रहा है",
  approvalsEmpty: "अभी सबसे कमज़ोर ज़िलों में किसी अंतर-ज़िला स्थानांतरण की ज़रूरत नहीं है।",
  escEmpty: "अभी कोई नहीं। ज़िलाधिकारी साप्ताहिक ब्रीफ से एस्केलेट करते हैं।",
  allDistricts: "सभी ज़िले",
  lgEyebrow: "राज्य तालिका", lgSub: "हर ज़िला सुदृढ़ता स्कोर से क्रमबद्ध; उसका आज स्क्रीन खोलने के लिए ज़िला चुनें",
  filterName: "ज़िले छाँटें", tierAll: "सभी", tierRes: "मज़बूत", tierWatch: "निगरानी", tierRisk: "जोखिम", noneAtRisk: "कोई ज़िला जोखिम में नहीं: हर स्कोर 45 या अधिक है।", noneWatch: "कोई ज़िला निगरानी में नहीं।",
  inspect: "खोलें", colFacilities: "सुविधाएँ", noDistricts: "कोई ज़िला मेल नहीं खाता।",
  inEyebrow: "पूरा भारत", inSub: "HMIS ज़िला लेजर से राज्य और ज़िला स्टॉक; डेमो राज्यों के लिए PHC स्तर का विवरण",
  tileStates: "रिपोर्ट करने वाले राज्य", tileStatesSub: (m: string) => m,
  tileNatStock: "स्टॉक के मध्य महीने", tileNatStockSub: "रिपोर्ट करने वाले राज्यों का मध्य",
  tileUnder: "एक महीने से कम वाले ज़िले", tileUnderSub: "एक महीने से कम स्टॉक वाले ज़िलों का हिस्सा",
  seEyebrow: "सिस्टम", seTitle: "सेटिंग और डेटा स्रोत", seSub: "आप कौन हैं, कौन सा डेटा देखते हैं, क्या-हो-अगर परीक्षण, और हर संख्या कहाँ से आती है",
  reset: "डिफ़ॉल्ट पर लौटें", resetHint: "डिफ़ॉल्ट भूमिका और ज़िला, वास्तविक डेटा, कोई परिदृश्य नहीं",
  secRole: "भूमिका", secBasis: "डेटा आधार", secWhatIf: "क्या-हो-अगर परिदृश्य", secFed: "फ़ेडरेटेड लर्निंग", secHealth: "डेटा स्थिति", secProv: "हर संख्या कहाँ से आती है",
  basisRealTitle: "वास्तविक HMIS लेजर", basisRealDesc: "मंत्रालय द्वारा प्रकाशित ज़िला स्टॉक, नवीनतम पूरा महीना मार्च 2020 (16 राज्यों के लिए FY 2020-21 अस्थायी)।",
  basisSimTitle: "मार्च 2026 तक सिम्युलेटेड", basisSimDesc: "हर ज़िले की वास्तविक श्रृंखला उसकी अपनी मौसमीयता और आपूर्ति पैटर्न से आगे बढ़ाई गई। केवल भारत दृश्य और भंडार स्टॉक बुक पर।",
  basisNote: "बाकी हर स्क्रीन पर सुविधा स्तर का स्टॉक सिम्युलेटेड है, वास्तविक ज़िला लेजर से बना।",
  scenarioNone: "कोई परिदृश्य नहीं", scenarioNoneDesc: "वर्तमान आँकड़े, कोई दबाव नहीं।",
  scenarioOnly: (u: string) => `${u} पर लागू`, allUnits: "सभी राज्य",
  intensity: "तीव्रता", active: "सक्रिय",
  fedRows: "नोड से बाहर गई पंक्तियाँ", fedRowsSub: "एग्रीगेटर पर मापा गया",
  fedNodes: "इस स्तर के नोड", fedNodesSub: (r: number) => `औसत के ${r} दौर`,
  fedAuc: "फ़ेडरेटेड AUC", fedAucSub: (l: string) => `अकेले प्रशिक्षित ${l} की तुलना में`,
  runLiveRound: "लाइव दौर चलाएँ", running: "चल रहा है", replayLbl: "रीप्ले", nodesTitle: "नोड",
};
export const sA = { en, hi };
