/** Strings for the second design pass (India view, league table, compare card, Move stock confirmation). Same keys in both languages. */
const en = {
  reporting: (n: number, of: number) => `${n} of ${of} states reporting`,
  phcDetail: "PHC-level detail",
  stateCol: "State",
  medianCol: "Median months",
  tapState: "Select a state on the map or in the table to see its districts.",
  scoreCard: "How the score works",
  scoreBands: "Bands",
  bandLow: "Under 45: at risk", bandMid: "45 to 60: watch", bandHigh: "Over 60: resilient",
  weights: [["Median days of stock", "40"], ["Share under 14 days", "20"], ["Staffing gap", "20"], ["Transfer latency", "10"], ["Reporting completeness", "10"]] as [string, string][],
  sortBy: "Sort by",
  sortScore: "Score", sortRed: "Red alerts", sortDays: "Median days",
  colScore: "Score", colDays: "Median days", colRed: "Red alerts",
  standsTitle: (d: string) => `Where ${d} stands`,
  rank: "Rank", scoreVsMedian: "Score vs state median", redVsMedian: "Red alerts vs state median",
  above: "Just above", below: "Just below", none: "None",
  approved: "Approved", viewTransit: "View in transit",
  transitEmpty: "Approved transfers appear here with their delivery status.",
};
const hi: typeof en = {
  reporting: (n: number, of: number) => `${of} में से ${n} राज्य रिपोर्ट कर रहे हैं`,
  phcDetail: "PHC स्तर का विवरण",
  stateCol: "राज्य",
  medianCol: "मध्य महीने",
  tapState: "ज़िले देखने के लिए नक्शे या तालिका में राज्य चुनें।",
  scoreCard: "स्कोर कैसे बनता है",
  scoreBands: "श्रेणियाँ",
  bandLow: "45 से कम: जोखिम", bandMid: "45 से 60: निगरानी", bandHigh: "60 से ऊपर: मज़बूत",
  weights: [["स्टॉक के मध्य दिन", "40"], ["14 दिन से कम का हिस्सा", "20"], ["स्टाफ़ की कमी", "20"], ["स्थानांतरण में देरी", "10"], ["रिपोर्टिंग पूर्णता", "10"]] as [string, string][],
  sortBy: "क्रम",
  sortScore: "स्कोर", sortRed: "लाल अलर्ट", sortDays: "मध्य दिन",
  colScore: "स्कोर", colDays: "मध्य दिन", colRed: "लाल अलर्ट",
  standsTitle: (d: string) => `${d} कहाँ है`,
  rank: "स्थान", scoreVsMedian: "स्कोर बनाम राज्य मध्य", redVsMedian: "लाल अलर्ट बनाम राज्य मध्य",
  above: "ठीक ऊपर", below: "ठीक नीचे", none: "कोई नहीं",
  approved: "स्वीकृत", viewTransit: "रास्ते में देखें",
  transitEmpty: "स्वीकृत स्थानांतरण यहाँ डिलीवरी स्थिति के साथ दिखेंगे।",
};
export const s2 = { en, hi };
